### ISSUE TITLE
TD FEF grant by July 15

### ISSUE THREAD

**Issue by StephMcNeely** [ForetCapitaleForest/actions#108]
- @StephMcNeely updated budget spreadsheet; seems a bit heavy on the HR $ and should include other materials that we may need (electric whipper snipper seems like an eligible expense) - @smlambert please review:  https://docs.google.com/spreadsheets/d/1qGBpuWoGPPHGaxSaqjfXCQVg0deqbnzg/edit?usp=sharing&ouid=105766462348532382756&rtpof=true&sd=true
- @MartinNesbitt to aim to send draft to Achillea by midday, July 13 (if reviewed by Steph or Shelley first)

**Comment by smlambert** [comment]
Related: https://github.com/ForetCapitaleForest/actions/issues/81 

I guess my note on the budget did not come through, but a hard 'no' on wood boards for ditch crossings, those are dangerous and I 'hate' that we use them currently.  The wood is slippery when wet and rots and breaks under weight.  A big insurance liability.  

My suggestion for ditch crossings is to use culverts covered by gravel.  When I said we will not use gravel in the meeting, I meant for the rest of the path, as once its applied, the area where it is applied can no longer be used for anything else (it is non-convertible back to agriculture according to Moe).

**Comment by smlambert** [comment]
Drainage pipe pricing [example](https://www.grainger.ca/en/product/p/WWG2DGG3).

Minimum number needed is 5 pieces x ~$200 each = $1000

The amount of gravel we used for the small greenhouse base plus parking was $500, so that is a good estimate to use (checking here for an [example](https://greelysand.com/shop/crushed-stone-sand-gravel/clear-limestone/)), guessing we need minimally 6 yards (which is 5 ditch crossings at 10ft long x 4ft wide x 1ft depth), which is $337, but lets up the amount to 10 yards for $458.50.

**Comment by smlambert** [comment]
I have updated the spreadsheet with those numbers, but accidentally nuked the estimate for so I put it $500 because I can not remember what it was.  For signs and printing, we can use the numbers Phil Mount sent (or see the pricing in the Treemendous Communities grant), but we should increase it slightly, as those prices were from several years ago, and I am sure they have increased since then.

**Comment by smlambert** [comment]
For grass seed, I am basing off of this eco-alternative grass seed [pricing](https://www.damseeds.com/collections/ggrass-seed/products/eco-alternative-mix), calculating that the main arteries of the path should be minimally 8ft wide (width to pass a tractor through), while secondary pathways are 4ft wide (mower & whippersnipper).  

Greely topsoil = $417.50 (for 10 yards)
Grass seed = $239.90 (for 20kg)

$657.40

**Comment by smlambert** [comment]
Cordless electric Whipper snipper [example](https://www.homedepot.ca/product/dewalt-20v-max-lithium-ion-cordless-brushless-14-inch-folding-string-trimmer-with-5ah-battery-and-charger/1001447100): ~$350

**Comment by StephMcNeely** [comment]
All sounds good Shelley and probably puts us just below $10,000 as a project total (I haven't looked)
@MartinNesbitt we may need to add in some items already paid for through other grants... Can you check if there is a requirement to show other Funding Sources for the project?

**Comment by MartinNesbitt** [comment]
Grant submitted. Approval in October
