### ISSUE TITLE
Biodiversity & Soil Analysis Project

### ISSUE THREAD

**Issue by InnesBuck** [ForetCapitaleForest/actions#122]
Early Stage Checklist
- [x] Project to be organized with either a team at Carleton University or the University of Guelph
- [x] Group brainstorming session, with FCF team
- [x] Document used as reference for the project: [Tiny Forest Zaanstad](https://edepot.wur.nl/446911)

**Comment by natashafcf** [comment]
@StephMcNeely  @smlambert  @InnesBuck 

FYI Paule sent this e-mail to do a CSL placement in the Fall (they can do this work if we want). The way this works is that a couple of students in a class will sign up to do this instead of let's say a Midterm or some other report. 

Here was her e-mail below:

Hello  Natasha

 
We’re calling upon community partners to participate in our community engagement programming for 2022-2023! Again, this year, you are invited to post placement opportunities for our Community Service Learning (CSL) program and/or Extracurricular Volunteering (EV) option.   

I would be happy to discuss with you different or new placement options you’d like to explore and consider.  This could include, for example, students supporting you with research or data analysis, front-line services, some communication work or other.  

[About CSL](https://www2.uottawa.ca/current-students/career-experiential-learning/volunteering/programs) 
As a quick refresher, CSL is an academic program where students complete roughly 30 community service hours with a non-profit organization or public agency as part of their course and reflect on their learnings. Courses and CSL placements are carefully matched to ensure course learning objectives and community partner needs are tightly aligned. If your organisation hasn’t done so already and wishes to participate in the CSL program, you will need to sign our CSL agreement.  
 

This fall, we offer CSL classes related to the following courses:

·       APA 3546: Marketing en sport et loisir (Marketing in sport and recreation)

·       LSR 2118: Recreation Program Development and Evaluation

·       LSR 2523 : Loisir et qualité de l’environnement (Recreation and environmental quality)

·       HSS 4331a : International Health

·       NUT 3501 : Nutrition publique et santé des populations 1 (Public Nutrition and Population Health 1)

·       SCI 3101: The Public Communication of Science


[About EV](https://www2.uottawa.ca/current-students/career-experiential-learning/volunteering/programs) 
EV is year-round volunteering opportunities with an organization like yours, offered outside of a course. These opportunities are posted and promoted to all university students who may select them.  

If you need a student for a specific project, please do not hesitate to post it directly on the Community Engagement Navigator, or to contact me to discuss whether any of our courses are a good fit. We could also discuss your long-term goals to see how our various programs could help support these. This [reference document](https://media.campaigner.com/media/58/588160/Marketing/PDF/Navigator_Reference%20Sheet_Partners_Oct2021.pdf) and this [video](https://www.youtube.com/watch?v=kEpXjJUI4UM) offers a step-by-step overview of our online tool (ex. creating an account, posting placements, etc.).   

We would be grateful if you could share this email with any of your colleagues you think may be interested in such programs. 
Please let us know if you have any questions or concerns.


Kind regards,

Paule Bhérer-Breton

**Comment by smlambert** [comment]
Tagging @Pepe-Fifi (Simona) also, as she has connected with U of Guelph also.

**Comment by InnesBuck** [comment]
[Folder](https://drive.google.com/drive/folders/1WZctccfQLK5t33nIYhVKD-rlbUhJ0E0G) in the shared drive has been made to keep the documents relevant to this project.

**Comment by InnesBuck** [comment]
Taking tree inventory of Tiny Forest
@Pepe-Fifi @InnesBuck @MartinNesbitt @smlambert 
- To note what species are in the tiny forest, in what quantities, where?
- High priority before all the leaves fall off
- [ ] Section 1
- [ ] Section 2
- [ ] Section 3
- [ ] Section 4

**Comment by Pepe-Fifi** [comment]
Great Innes; I will start an inventory of field/section 1 next week.

**Comment by Pepe-Fifi** [comment]
Hey @InnesBuck and @MartinNesbitt , When you have a draft inventory for the sections you already finished ( 1, 2, 3? ) please share them in the folder.  I found an interesting tiny forest handbook that I uploaded there.

**Comment by InnesBuck** [comment]
Hi @Pepe-Fifi I have added the [inventory](https://docs.google.com/spreadsheets/d/1kwoH17cD_euiUZ1HqfAaGwicZnZ5iA2BwaDzIAE3pw4/edit#gid=1930698360) Google sheet to the drive. Marty and I have completed section 1 and part of section 2. We will be continuing next week.

**Comment by Pepe-Fifi** [comment]
Thank you, Innes. Great work so far!

**Comment by InnesBuck** [comment]
Here is a copy of the [Meeting Minutes](https://docs.google.com/document/d/1xTb8lfr8E_gT6iNXKEqTD54rhJWf04DR2Cwjvfhvckg/edit). It is found in the folder for this project on drive.

**Comment by Pepe-Fifi** [comment]
Thank you very much, Innes!

Simona

**Comment by smlambert** [comment]
This project is underway, with University of Guelph.

Initial Malaise trap samples and soil samples have been sent by @Pepe-Fifi (who is our FCF lead for this project) to Katherine (who is a student dedicated to this project for the remainder of the year).  

Closing this issue as it was created to _kick off the project_ which is now completed.
