### ISSUE TITLE
Mer Bleue walkabout

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#23]
This is scheduled for the afternoon of April 29th.  

Meet at Ottawa Farm Fresh ([map](https://goo.gl/maps/4kSX5mxZL8pYFaCP6)) at 1pm

**Comment by StephMcNeely** [comment]
Here are a few quick thoughts from our visit to the NCC sites last Friday (April 29, 2022) with Cedric and Bruno.

Have a look here:
https://wakenney.github.io/NCCVisitedPoints.html

I put some points on our map of the NCC sites.  It isn’t pretty but I needed to get my head around where we were.

The Russell Rd site looks doable with good access.  The entire property shown on the map isn’t available for some reason, just a strip on either side of the creek (about 20m wide each side).  You can switch the polygons off or select the basemap from the hamburger icon at the top right to get a better look.

I called the other two sites Farmer’s Way East and West.  We walked along the track from Farmer’s Way in either direction, much to the dismay of the engineer on the 2:45 Via from Montreal!  Cedric suggested that the Farmer’s Way East site is also smaller than the property boundaries suggest.  We’d have to check this out further with him.  Access could be gained from Russell Rd to the east.  Farmer’s Way West is a big site and the bit we walked on is very wet right now.  We were concerned about safe access (the railbed is out of the question) but if you look to the extreme west of the site, you’ll see a City of Ottawa ROW running southwest to northeast from Anderson Rd to the site.  It’s about 900m but this might work if you could get access to an ATV and small tailer.  Note that the two Farmer’s way sites were classed as High Priority (red) in our original GIS analysis.

Clearly (I guess) not ALL of the sites can be planted because of excessive water and existing tree (willow) cover.  If you thought they had potential, a more in-depth site walk would be necessary.  At least we know where three site are for now.

**Comment by smlambert** [comment]
Mark action as complete.
