### ISSUE TITLE
create Hugel mound in field 3 in wettest area. wood chips.

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#299]

**Comment by MartinNesbitt** [comment]
Yes, I have budget going for the Aviva event. Could you please look through it when you have time.  https://docs.google.com/spreadsheets/d/1eDv_6NrquPrCvSYylpNAIdvgryhiA-QT/edit?usp=sharing&ouid=104658172105924753645&rtpof=true&sd=true 

I have a few questions on the second page @smlambert @StephMcNeely

**Comment by smlambert** [comment]
Think your questions were answered in the document.  

The remaining action in order to close this one is to move many wheelbarrows of wood chips to this location (to form a very very thick mulch in between the 2 rows, 1 ft thick would be great, and would help towards this open issue: https://github.com/ForetCapitaleForest/actions/issues/296

**Comment by StephMcNeely** [comment]
Hi Marty
Thanks for putting this together. I took a quick look at the invoice and
suggest $500 for cost of trees (regardless of whether they were donated,
etc.). That would probably cover some delivery charges.
I am working somewhat blind as the second page doesn't say what the TC
contract can or can't include.
Not sure we should be charging for staff kms to our typical workplace -
unless TC said otherwise.

I'll take another look once you have updated.  And let me know if you have
any other questions.

Thanks
Stephanie
