### ISSUE TITLE
Transplant Z number of forb seedling starts into 1g pots that are needed for TinyForestsSite1, others can either be potted up for TinyForestsSite2 and TinyForestsSite3, or planted into seedling area. For FCF to do. Ready within a month from now. end of may

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#305]

**Comment by smlambert** [comment]
@gabbylajeunesse and @KaviGK transplanted a few of these last week.  Many more to go.  

Will need many more additional small pots for this purpose.

**Comment by StephMcNeely** [comment]
@smlambert would this be a suitable job for a bunch of federal public servants from my sister-in-law's Environmental Assessment Agency team? They are looking to volunteer anytime from June 19th - is that too late?
Could it be one of jobs we ask volunteers to help with next week at Volunteer event?

**Comment by smlambert** [comment]
yes for both groups, though it is 'delicate' work, so would not want to have a bunch perish because they were handled roughly, we have thousands of forbs seedlings, and will be potting up for "a while"... 

our main problem is lack of pots... 
for these, we are looking for small pots about the same size as our paper cups, prefer if they were square to fit into trays in a stable manner

**Comment by smlambert** [comment]
Closing as dup of #335
