### ISSUE TITLE
Walking Path links to include in Redbarnloop.ca

### ISSUE THREAD

**Issue by KaviGK** [ForetCapitaleForest/actions#503]
Walking Path survey & Base of operations Virtual tour links to be included into Redbarnloop.ca as part of the TD FEF grant requirements. Pls see document below for instructions . 

https://docs.google.com/document/d/1CXQrXHBhQV50ni0P71Va7_8EpnsoYjD77nEIZqRjUgY/edit

**Comment by smlambert** [comment]
redbarnloop.ca pages are updated with links to the survey

May want to ensure that the survey questions look consistent (some paragraphs are capitalized, others are not).

Base of Operations digital tour is linked on the home page of redbarnloop.ca (but the digital tour needs some updates and we will have to look at how we embed the maps directly into the website, instead of linking off to it).  Winter project.
